export const userConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}

export const todoConstant = {
    GET_ALL_TODO_REQUEST: 'GET_ALL_TODO_REQUEST',
    GET_ALL_TODO_SUCCESS: 'GET_ALL_TODO_SUCCESS',
    GET_ALL_TODO_FAILURE: 'GET_ALL_TODO_FAILURE',
}

export const resetConstant = {
    RESET_USER: 'RESET_USER'
}